# Generated by Django 3.0.3 on 2020-02-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='service',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Lunch Time', 'Lunch Time'), ('Evening', 'Evening'), ('Night', 'Night')], max_length=200, null=True),
        ),
    ]
