# Generated by Django 3.0.3 on 2020-02-28 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0002_book_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='service',
            new_name='time',
        ),
    ]
